// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcITtdNBhemjGtAGZNUhOvbmzH-HSihnU',
    appId: '1:410682798773:web:03f8a76c0375046086c4fc',
    messagingSenderId: '410682798773',
    projectId: 'edtech-3f6fe',
    authDomain: 'edtech-3f6fe.firebaseapp.com',
    storageBucket: 'edtech-3f6fe.firebasestorage.app',
    measurementId: 'G-B1K4HCG09K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_XDoEFbpz1EiolJqXy28_bASRWStBVv0',
    appId: '1:410682798773:android:2c6a62abb458b3f086c4fc',
    messagingSenderId: '410682798773',
    projectId: 'edtech-3f6fe',
    storageBucket: 'edtech-3f6fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9yq3hmlsowp3FEZADO3iYc3EDQpWt3es',
    appId: '1:410682798773:ios:a23833e0d4b2678a86c4fc',
    messagingSenderId: '410682798773',
    projectId: 'edtech-3f6fe',
    storageBucket: 'edtech-3f6fe.firebasestorage.app',
    iosClientId:
        '410682798773-pghlg1d30lm1n8mvdtleob2rcr0jbn6d.apps.googleusercontent.com',
    iosBundleId: 'com.bitwiseacademy.bitwiseAcademy',
  );
}
